apiVersion: v1
kind: Pod
metadata:
    name: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
    containers:
    - name: {{ .Chart.Name }}
      image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do echo {{ .Values.message }} && sleep 10; done; "]
